pro    Creating the base tables for the PL/SQL assignment...

drop table payroll_checks purge;
drop table employees purge;
drop table departments purge;

create table departments (
   department_id   number generated by default as identity primary key,
   department_name varchar2(60) not null
);

create table employees (
   employee_id   number generated by default as identity primary key,
   first_name    varchar2(40) not null,
   last_name     varchar2(40) not null,
   department_id number,
   salary        number(10,2) not null,
   hire_date     date,
   annual_bonus  number(10,2) default 0,
   constraint fk_emp_dept foreign key ( department_id )
      references departments ( department_id )
);

create table payroll_checks (
   employee_id   number primary key,
   gross_salary  number(10,2),
   tax_amount    number(10,2),
   net_salary    number(10,2),
   review_status varchar2(30),
   constraint fk_payroll_emp foreign key ( employee_id )
      references employees ( employee_id )
);

insert into departments ( department_name ) values
   ( 'Finance' );

insert into departments ( department_name ) values
   ( 'HR' );

insert into departments ( department_name ) values
   ( 'IT' );

insert into departments ( department_name ) values
   ( 'Operations' );

insert into employees (
   first_name,
   last_name,
   department_id,
   salary,
   hire_date,
   annual_bonus
) values
   ( 'Alice',
     'Mugisha',
     1,
     5200,
     date '2020-05-10',
     350 );

insert into employees (
   first_name,
   last_name,
   department_id,
   salary,
   hire_date,
   annual_bonus
) values
   ( 'Eric',
     'Ndayisaba',
     3,
     7800,
     date '2018-02-15',
     900 );

insert into employees (
   first_name,
   last_name,
   department_id,
   salary,
   hire_date,
   annual_bonus
) values
   ( 'Grace',
     'Uwimana',
     2,
     4200,
     date '2021-09-01',
     200 );

insert into employees (
   first_name,
   last_name,
   department_id,
   salary,
   hire_date,
   annual_bonus
) values
   ( 'John',
     'Kagabo',
     4,
     6100,
     date '2016-11-12',
     650 );

insert into payroll_checks (
   employee_id,
   gross_salary,
   tax_amount,
   net_salary,
   review_status
) values
   ( 1,
     5200,
     760,
     4440,
     'APPROVED' );

insert into payroll_checks (
   employee_id,
   gross_salary,
   tax_amount,
   net_salary,
   review_status
) values
   ( 2,
     7800,
     1200,
     6600,
     'APPROVED' );

insert into payroll_checks (
   employee_id,
   gross_salary,
   tax_amount,
   net_salary,
   review_status
) values
   ( 3,
     4200,
     470,
     3730,
     'REVIEW' );

insert into payroll_checks (
   employee_id,
   gross_salary,
   tax_amount,
   net_salary,
   review_status
) values
   ( 4,
     6100,
     920,
     5180,
     'APPROVED' );

commit;

pro    Tables created successfully.